FROM node:20-alpine AS dev
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app
COPY --from=dev /app/package*.json .
RUN npm ci --omit=dev
COPY --from=dev /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/main.js"]