# Stage 1: Build Angular static assets
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
#RUN npm run build -- --configuration production
CMD ["npm", "run", "build"]
#/app/dist/learning-node/browser
